# Deploys `master` builds to the public hosting
name: Deploy to prod

# Controls when the workflow will run
on:
  # Triggers the workflow on push events only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prod-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 🚚 Get latest source code
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: 🧰 Setup Node.js environment
        uses: actions/setup-node@v2

      # Build the website
      - name: 🔨 Build project
        run: |
          node -v
          npm -v
          npm ci --production
          npm run build

      - name: 🚀 Upload to Netsons
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          # ftp server
          server: ftp.eclubpolimi.it
          # ftp username
          username: git@eclubpolimi.it
          # ftp password
          password: ${{ secrets.FTP_DEPLOY_PASSWORD }}
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          protocol: ftps
          # Folder to upload from, must end with trailing slash /
          local-dir: build/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: public_html/
          # Testing only: Ouputs a list of files that will be created/modified to sync your source without making any actual changes
          dry-run: false
