# Deploys `master` builds to the public hosting
name: Deploy master

on:
  # Triggers the workflow on push events only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Disallow multiple instances of this action to run at the same time (for ftp upload to work correctly)
concurrency: deploy

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest source code
        uses: actions/checkout@v2

      - name: 🧰 Setup Node.js environment
        uses: actions/setup-node@v2

      # Build the website
      - name: 🔨 Build project
        env:
          CMS_GRAPHQL_ENDPOINT: ${{ secrets.CMS_GRAPHQL_ENDPOINT }}
          CMS_ACCESS_TOKEN: ${{ secrets.CMS_ACCESS_TOKEN }}
          CMS_PREVIEW_ACCESS_TOKEN: ${{ secrets.CMS_PREVIEW_ACCESS_TOKEN }}
        run: |
          node -v
          npm -v
          npm install
          npm run build

      - name: 🚀 Upload to Netsons
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          # ftp server
          server: ftp.eclubpolimi.it
          # ftp username
          username: git@eclubpolimi.it
          # ftp password
          password: ${{ secrets.FTP_DEPLOY_PASSWORD }}
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          protocol: ftps
          # Folder to upload from, must end with trailing slash /
          local-dir: build/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: public_html/
          # Testing only: Ouputs a list of files that will be created/modified to sync your source without making any actual changes
          dry-run: false
